### ISSUE TITLE
DeviceProperties add 显示问题

### ISSUE THREAD

**Issue by alezh** [xieguozhong/opencoreConfiguratorOnline#1]
![image](https://user-images.githubusercontent.com/5153676/101453227-fb930e00-3969-11eb-9798-ff5cde696734.png)
只能显示4～5行。后面的数据都是空白

源文件图
![image](https://user-images.githubusercontent.com/5153676/101453498-66444980-396a-11eb-877f-e44afccc213d.png)

**Comment by xieguozhong** [comment]
感谢，感动的我哇哇的，麻烦提供下你的config.plist文件给我，谢谢

**Comment by xieguozhong** [comment]
搞定了， jqgrid没有设置rowNum，所以把后面的数据隐藏了，现在设置rowNum: 9000 就ok了
